import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Navigate, Route, Routes } from 'react-router-dom';
import { lazy, Suspense } from 'react';
import MainLayout from '../app/layouts/MainLayout';
import AuthLayout from '../app/layouts/AuthLayout';
import SimpleAuthLayout from '../app/layouts/SimpleAuthLayout';
import AdminLayout from '../app/layouts/AdminLayout';
import ProtectedRoute from '../components/ProtectedRoute';
import LoadingOverlay from '../components/feedback/LoadingOverlay';
// Lazy load page components for better performance
const HomePage = lazy(() => import('../app/pages/HomePage'));
const CatalogPage = lazy(() => import('../app/pages/CatalogPage'));
const BookDetailPage = lazy(() => import('../app/pages/BookDetailPage'));
const ReaderPage = lazy(() => import('../app/pages/ReaderPage'));
const DashboardPage = lazy(() => import('../app/pages/DashboardPage'));
const AnalyticsPage = lazy(() => import('../app/pages/AnalyticsPage'));
const AnalyticsTimePage = lazy(() => import('../app/pages/analytics/AnalyticsTimePage'));
const AnalyticsStreakPage = lazy(() => import('../app/pages/analytics/AnalyticsStreakPage'));
const AnalyticsPagesPage = lazy(() => import('../app/pages/analytics/AnalyticsPagesPage'));
const AnalyticsCompletionPage = lazy(() => import('../app/pages/analytics/AnalyticsCompletionPage'));
const CompletedBooksPage = lazy(() => import('../app/pages/CompletedBooksPage'));
const ProfilePage = lazy(() => import('../app/pages/ProfilePage'));
const LibrisAIPage = lazy(() => import('../app/pages/LibrisAIPage'));
const LoginPage = lazy(() => import('../app/pages/LoginPage'));
const RegisterPage = lazy(() => import('../app/pages/RegisterPage'));
const ForgotPasswordPage = lazy(() => import('../app/pages/ForgotPasswordPage'));
const ResetCodePage = lazy(() => import('../app/pages/ResetCodePage'));
const NewPasswordPage = lazy(() => import('../app/pages/NewPasswordPage'));
const VisitorAccessPage = lazy(() => import('../app/pages/VisitorAccessPage'));
const VisitorRegisterPage = lazy(() => import('../app/pages/VisitorRegisterPage'));
const SubscriptionPlansPage = lazy(() => import('../app/pages/subscription/SubscriptionPlansPage'));
const SubscriptionPaymentPage = lazy(() => import('../app/pages/subscription/SubscriptionPaymentPage'));
const MobileMoneyPaymentPage = lazy(() => import('../app/pages/subscription/MobileMoneyPaymentPage'));
const CardPaymentPage = lazy(() => import('../app/pages/subscription/CardPaymentPage'));
const PayPalPaymentPage = lazy(() => import('../app/pages/subscription/PayPalPaymentPage'));
const AdminOverviewPage = lazy(() => import('../app/pages/admin/AdminOverviewPage'));
const AdminUsersPage = lazy(() => import('../app/pages/admin/AdminUsersPage'));
const AdminSubscriptionsPage = lazy(() => import('../app/pages/admin/AdminSubscriptionsPage'));
const AdminBooksPage = lazy(() => import('../app/pages/admin/AdminBooksPage'));
const AdminCategoriesPage = lazy(() => import('../app/pages/admin/AdminCategoriesPage'));
const UnauthorizedPage = lazy(() => import('../app/pages/UnauthorizedPage'));
const AppRoutes = () => (_jsx(Suspense, { fallback: _jsx(LoadingOverlay, { label: "Loading..." }), children: _jsxs(Routes, { children: [_jsxs(Route, { element: _jsx(MainLayout, {}), children: [_jsx(Route, { index: true, element: _jsx(HomePage, {}) }), _jsx(Route, { path: "catalog", element: _jsx(CatalogPage, {}) }), _jsx(Route, { path: "catalog/:bookId", element: _jsx(BookDetailPage, {}) }), _jsx(Route, { path: "reader/:bookId", element: _jsx(ProtectedRoute, { children: _jsx(ReaderPage, {}) }) }), _jsx(Route, { path: "dashboard", element: _jsx(ProtectedRoute, { children: _jsx(DashboardPage, {}) }) }), _jsx(Route, { path: "profile", element: _jsx(ProtectedRoute, { children: _jsx(ProfilePage, {}) }) }), _jsx(Route, { path: "libris-ai", element: _jsx(ProtectedRoute, { children: _jsx(LibrisAIPage, {}) }) }), _jsx(Route, { path: "analytics", element: _jsx(ProtectedRoute, { children: _jsx(AnalyticsPage, {}) }) }), _jsx(Route, { path: "analytics/time", element: _jsx(ProtectedRoute, { children: _jsx(AnalyticsTimePage, {}) }) }), _jsx(Route, { path: "analytics/streak", element: _jsx(ProtectedRoute, { children: _jsx(AnalyticsStreakPage, {}) }) }), _jsx(Route, { path: "analytics/pages", element: _jsx(ProtectedRoute, { children: _jsx(AnalyticsPagesPage, {}) }) }), _jsx(Route, { path: "analytics/completion", element: _jsx(ProtectedRoute, { children: _jsx(AnalyticsCompletionPage, {}) }) }), _jsx(Route, { path: "books/completed", element: _jsx(ProtectedRoute, { children: _jsx(CompletedBooksPage, {}) }) })] }), _jsxs(Route, { element: _jsx(AuthLayout, {}), children: [_jsx(Route, { path: "login", element: _jsx(LoginPage, {}) }), _jsx(Route, { path: "register", element: _jsx(RegisterPage, {}) }), _jsx(Route, { path: "visitor-access", element: _jsx(VisitorAccessPage, {}) }), _jsx(Route, { path: "visitor-register", element: _jsx(VisitorRegisterPage, {}) })] }), _jsxs(Route, { element: _jsx(SimpleAuthLayout, {}), children: [_jsx(Route, { path: "forgot-password", element: _jsx(ForgotPasswordPage, {}) }), _jsx(Route, { path: "reset-code", element: _jsx(ResetCodePage, {}) }), _jsx(Route, { path: "new-password", element: _jsx(NewPasswordPage, {}) }), _jsx(Route, { path: "subscription/plans", element: _jsx(ProtectedRoute, { children: _jsx(SubscriptionPlansPage, {}) }) }), _jsx(Route, { path: "subscription/payment/:planId", element: _jsx(ProtectedRoute, { children: _jsx(SubscriptionPaymentPage, {}) }) }), _jsx(Route, { path: "subscription/payment/:planId/mobile-money/:provider?", element: _jsx(ProtectedRoute, { children: _jsx(MobileMoneyPaymentPage, {}) }) }), _jsx(Route, { path: "subscription/payment/:planId/card", element: _jsx(ProtectedRoute, { children: _jsx(CardPaymentPage, {}) }) }), _jsx(Route, { path: "subscription/payment/:planId/paypal", element: _jsx(ProtectedRoute, { children: _jsx(PayPalPaymentPage, {}) }) })] }), _jsxs(Route, { path: "admin", element: _jsx(ProtectedRoute, { roles: ['ADMIN'], children: _jsx(AdminLayout, {}) }), children: [_jsx(Route, { index: true, element: _jsx(Navigate, { to: "overview", replace: true }) }), _jsx(Route, { path: "overview", element: _jsx(AdminOverviewPage, {}) }), _jsx(Route, { path: "users", element: _jsx(AdminUsersPage, {}) }), _jsx(Route, { path: "subscriptions", element: _jsx(AdminSubscriptionsPage, {}) }), _jsx(Route, { path: "books", element: _jsx(AdminBooksPage, {}) }), _jsx(Route, { path: "categories", element: _jsx(AdminCategoriesPage, {}) })] }), _jsx(Route, { path: "unauthorized", element: _jsx(UnauthorizedPage, {}) }), _jsx(Route, { path: "*", element: _jsx(Navigate, { to: "/", replace: true }) })] }) }));
export default AppRoutes;
