# Generated by Django 4.2.7 on 2026-02-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_book_cloudinary_public_id_book_file_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('event_type', models.CharField(max_length=225)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Book Event',
                'verbose_name_plural': 'Book Events',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='ai_tags',
            field=models.JSONField(default=list, help_text='List of AI-generated tags'),
        ),
        migrations.AddField(
            model_name='book',
            name='embedding_vector',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='read_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='trending_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='like_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_published', '-view_count'], name='catalog_boo_is_publ_ecc3e6_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_published', '-created_at'], name='catalog_boo_is_publ_b5075a_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_published', '-like_count'], name='catalog_boo_is_publ_a7f41f_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author', 'is_published'], name='catalog_boo_author__987383_idx'),
        ),
        migrations.AddIndex(
            model_name='bookevent',
            index=models.Index(fields=['book_id', 'event_type'], name='catalog_boo_book_id_848742_idx'),
        ),
        migrations.AddIndex(
            model_name='bookevent',
            index=models.Index(fields=['user_id', 'event_type'], name='catalog_boo_user_id_54d5df_idx'),
        ),
    ]
