# Generated by Django 4.2.7 on 2026-02-21 19:05

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_bookevent_book_ai_summary_book_ai_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='embedding_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
