# Generated by Django 4.2.7 on 2026-02-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_book_embedding_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='visual_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
